# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170707_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.RemoveField(
            model_name='item',
            name='list',
        ),
    ]
